/*
 * Autogenerated by libtcod's hmtool.
 *
 * Modified and adapted for GT
 */


#include <stdlib.h>
#include <libtcod.h>
#include "gt.h"
#include "world.h"

// size of the heightmap
#define HM_WIDTH XSIZE
#define HM_HEIGHT YSIZE

TCOD_random_t rnd=NULL;
TCOD_noise_t noise=NULL;

#include <math.h>

void addHill(TCOD_heightmap_t *hm,int nbHill, float baseRadius, float radiusVar, float height)
{
	int i;
	for (i=0; i<  nbHill; i++ ) {
		float hillMinRadius=baseRadius*(1.0f-radiusVar);
		float hillMaxRadius=baseRadius*(1.0f+radiusVar);
		float radius = TCOD_random_get_float(rnd,hillMinRadius, hillMaxRadius);
		float theta = TCOD_random_get_float(rnd,0.0f, 6.283185f); // between 0 and 2Pi
		float dist = TCOD_random_get_float(rnd,0.0f, (float)MIN(HM_WIDTH,HM_HEIGHT)/2 - radius);
		int xh = (int) (HM_WIDTH/2 + cos(theta) * dist);
		int yh = (int) (HM_HEIGHT/2 + sin(theta) * dist);
		TCOD_heightmap_add_hill(hm,(float)xh,(float)yh,radius,height);
	}
}
// function building the heightmap
void buildMap(TCOD_heightmap_t *hm)
{
//	TCOD_heightmap_scale_fbm(hm,noise,1,1,0,0,6,0.5,1);
//	scaleFbmDelta += HM_WIDTH;
	TCOD_heightmap_add_fbm(hm,noise,1,1,0,0,6,0.5,1);
}

// test code to print the heightmap
// to compile this file on Linux :
//  gcc hm.c -o hm -I include/ -L . -ltcod
// to compile this file on Windows/mingw32 :
//  gcc hm.c -o hm.exe -I include/ -L lib -ltcod-mingw
void generate_heightmap(TCOD_heightmap_t *hm)
{
	//rnd=TCOD_random_new_from_seed(1174635518U);
        rnd = TCOD_random_new(TCOD_RNG_CMWC);
	noise = TCOD_noise_new(2,TCOD_NOISE_DEFAULT_HURST,TCOD_NOISE_DEFAULT_LACUNARITY,rnd);
	buildMap(hm);
}
