#ifndef OBJDEFINES_H
#define OBJDEFINES_H

#define FIRST_WEAPON 1
#define LONG_SWORD 1
#define SHORT_SWORD 2
#define TWO_HANDED_SWORD 3
#define SMALL_AXE 4
#define LARGE_AXE 5
#define TWO_HANDED_AXE 6
#define DAGGER 7
#define BROADSWORD 8
#define GIANT_SWORD 9
#define LAST_WEAPON 9
#define P577_STARHAMMER 11
#define P9_TWO_HANDED_SWORD_OF_HOLY_FUCK 12
#define FIRST_ARMOR 14
#define CHAIN_MAIL 14
#define HELMET 15
#define LAST_ARMOR 15
#define FIRST_WAND 18
#define WAND_OF_FIRE 18
#define WAND_OF_ICE 19
#define WAND_OF_HEALING 20
#define WAND_OF_THUNDER 21
#define WAND_OF_LIGHTNING 22
#define WAND_OF_FEAR 23
#define LAST_WAND 23
#define RED_HERRING 25
#define HEAVY_METAL_FRUIT 26
#define AMBER_ALE 27
#define FIRST_RING 29
#define RING_OF_CHAMELEONISM 29
#define P1_RING_OF_WISDOM 30
#define P2_RING_OF_GREAT_WISDOM 31
#define P4_RING_OF_THE_PHILOSOPHER 32
#define RING_OF_INVISIBILITY 33
#define RING_OF_REGENERATION 34
#define RING_OF_FIRE_RESISTANCE 35
#define RING_OF_FIRE 36
#define P1_RING_OF_PROTECTION 37
#define P2_RING_OF_GREAT_PROTECTION 38
#define P5_RING_OF_DIVINE_PROTECTION 39
#define RING_OF_HIBERNATING_DIGESTION 40
#define RING_OF_LIGHT 41
#define LAST_RING 41

#define NUM_OBJECTS 43

#endif
