#ifndef OBJDEFINES_H
#define OBJDEFINES_H

#define FIRST_WEAPON 1
#define LONG_SWORD 1
#define SHORT_SWORD 2
#define TWO_HANDED_SWORD 3
#define SMALL_AXE 4
#define LARGE_AXE 5
#define TWO_HANDED_AXE 6
#define DAGGER 7
#define BROADSWORD 8
#define GIANT_SWORD 9
#define MORNING_STAR 10
#define WARHAMMER 11
#define STICK 12
#define LAST_WEAPON 12
#define P577_STARHAMMER 14
#define P9_TWO_HANDED_SWORD_OF_HOLY_FUCK 15
#define FIRST_ARMOR 17
#define LEATHER_ARMOR 17
#define STUDDED_LEATHER_ARMOR 18
#define RING_MAIL 19
#define SCALE_MAIL 20
#define CHAIN_MAIL 21
#define SPLINT_MAIL 22
#define PLATE_MAIL 23
#define FIELD_PLATE_ARMOR 24
#define FULL_PLATE_ARMOR 25
#define HELMET 26
#define SMALL_SHIELD 27
#define LARGE_SHIELD 28
#define LEATHER_GLOVES 29
#define LEATHER_SHOES 30
#define LAST_ARMOR 30
#define FIRST_WAND 33
#define WAND_OF_FIRE 33
#define WAND_OF_ICE 34
#define WAND_OF_HEALING 35
#define WAND_OF_THUNDER 36
#define WAND_OF_LIGHTNING 37
#define WAND_OF_FEAR 38
#define LAST_WAND 38
#define RED_HERRING 40
#define HEAVY_METAL_FRUIT 41
#define AMBER_ALE 42
#define FIRST_RING 44
#define RING_OF_CHAMELEONISM 44
#define P1_RING_OF_WISDOM 45
#define P2_RING_OF_GREAT_WISDOM 46
#define P4_RING_OF_THE_PHILOSOPHER 47
#define RING_OF_INVISIBILITY 48
#define RING_OF_REGENERATION 49
#define RING_OF_FIRE_RESISTANCE 50
#define RING_OF_FIRE 51
#define P1_RING_OF_PROTECTION 52
#define P2_RING_OF_GREAT_PROTECTION 53
#define P5_RING_OF_DIVINE_PROTECTION 54
#define RING_OF_HIBERNATING_DIGESTION 55
#define RING_OF_LIGHT 56
#define LAST_RING 56

#define NUM_OBJECTS 58

#endif
